markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
title: NetCafe
description: Joe's Blog, powered by Jekyll...
feed: http://a.pop925.net/atom.xml

author: Steven Pan

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
