markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html
url: 
lsi: false
pygments: false
safe: true
auto: true 

paginate: 5
paginate_path: "page:num"

# presonal config
title: NetCafe
description: Joe's Blog...
feed: http://www.hijoe.net/atom.xml

author: Joe

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
